# Generated by Django 4.2.4 on 2023-08-08 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="is_completed",
        ),
    ]
